### ISSUE TITLE
[1.12.2] Crash when killing haunted tool

### ISSUE THREAD

**Issue by PapiDimmi** [Daveyx0/PrimitiveMobs#1]
I killed a haunted golden axe, and then I instantly crashed.

Crash log: https://pastebin.com/raw/xmKvjpm3

From what I can tell, there’s a compatibility issue with iChun’s [Morph](https://minecraft.curseforge.com/projects/morph) mod. Every time I kill a mob I haven’t killed before, I acquire the mob, and an effect takes place. That might be what crashed the game.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Primitive Mobs version**: 1.1beta
**iChunUtil version**: 7.1.2
**Morph version**: 7.1.0

**Comment by Vazkii** [comment]
Definitely looks like a morph issue

**Comment by PapiDimmi** [comment]
Yeah, I know. I’m not sure if @Daveyx0 has to fix this or if @iChun has to fix it.

**Comment by Vazkii** [comment]
It doesn't appear to be on our end

**Comment by PapiDimmi** [comment]
I reported it to Morph’s repository.
iChun/Morph/issues/895

**Comment by iChun** [comment]
TIL getEntityTexture is @Nullable. Definitely an issue on my end.

**Comment by PapiDimmi** [comment]
I also crashed upon trying to morph into a treasure slime from Primitive Mobs.

Crash log: https://pastebin.com/raw/803XRN2p

I’m not sure if this issue is related.
