### ISSUE TITLE
Brain slimes attaching when not attached and killing player forever from afar

### ISSUE THREAD

**Issue by Darkmega18** [Daveyx0/PrimitiveMobs#102]
The brain slimes are being buggy. I can hear their jumping sounds sometimes but eventually even if they're stuck at the bottom of a river, on the other side of the hill or missed their jump sometimes they attach even though they are nowhere near you. When this happens they eat you constantly with no fear or being attacked as if they were there normally and then you die cause you can't hit something thats not there. I've been killed twice in two different worlds by this occurring. Although found I can go under two block high spaces to knock them off if lucky, but still nearly died as I have no health regeneration and only regenning absorption shields in my pack. 

I'm turning them off, but just know thats an issue with if not just your mod, possibly a compatibility somewhere.

one of these log spams I noticed I had gotten for the brief time I was on the server (although first time it happened was singleplayer) could potentially be related to them. but not sure. since theres stuff about packets, some things about library lib and some about head look rotations and stuff...

https://pastebin.com/anis08g6

**Comment by Daveyx0** [comment]
Hopefully fixed with the changes made to the Brain Slime attach code for the next version

**Comment by Darkmega18** [comment]
hopefully. xD
