### ISSUE TITLE
Lily Lurkers suffocate in mud, soulsand, ect...

### ISSUE THREAD

**Issue by FamiliarGecko** [Daveyx0/PrimitiveMobs#105]
If the block directly below water is something that you sink into a little bit (like soulsand or mud) lily lurkers will start to suffocate if they touch them.

And in biomes o plenty, in their natural environment, mud is common in the bottom of lakes. So it's not a rare sight to see lily lurkers commit suicide.

![2018-07-10_19 00 59](https://user-images.githubusercontent.com/33727121/42525580-ce56c308-8473-11e8-8728-46b0c92fff21.png)
![2018-07-10_19 01 50](https://user-images.githubusercontent.com/33727121/42525619-e8297e6a-8473-11e8-8868-dca484d0e63c.png)
![2018-07-10_19 01 51](https://user-images.githubusercontent.com/33727121/42525628-eec13eac-8473-11e8-9949-9dddc90d5b8c.png)

**Comment by Daveyx0** [comment]
Confirmed this as well. Odd. Will check. Thanks

**Comment by Daveyx0** [comment]
Fixed in next version
