### ISSUE TITLE
translation files (zh_TW.lang and ja_JP.lang)

### ISSUE THREAD

**Issue by ckhomo** [Daveyx0/PrimitiveMobs#106]
Dear developers,

I made 2 translation files. One is traditional chinese , another is japanese , apparently.
Thank you for the development and maintenance to this mod.

Sincerely,
[ja_JP.lang.txt](https://github.com/Daveyx0/PrimitiveMobs/files/2201784/ja_JP.lang.txt)
[zh_TW.lang.txt](https://github.com/Daveyx0/PrimitiveMobs/files/2201785/zh_TW.lang.txt)

**Comment by Daveyx0** [comment]
Thanks a bunch. I added them to my repository
