### ISSUE TITLE
Suicide Spiderfamily 

### ISSUE THREAD

**Issue by vincania** [Daveyx0/PrimitiveMobs#107]
This is not a bug just something worth mentioning. While exploring a cave i came across a spider family. The mother was climbing up the wall and killed the one little guy on her back...of course a new one respawned and died again. I got free string from that but this could probably cause issues if there are many items lying around...maybe there is a workaround for that? probably make the one on the mothers back immune against suffocation damage?
Great mod by the way! I don't know how rare the lost miner is but his trades are pretty over powered. Could use some rebalancing! Like it! Thx for the work!

**Comment by Daveyx0** [comment]
Thanks, I fixed this for the next version
