### ISSUE TITLE
[optional balance suggestion] A fuse length on the rocket creeper's leap.

### ISSUE THREAD

**Issue by Darkmega18** [Daveyx0/PrimitiveMobs#108]
I would like to suggest the ability in the configs to enable a "rocket launch delay" on the rocket creeper that stops them instead instantly divebombing you and being really salty like that. where instead they charge up for 1.5 seconds like normal, then if they're still ignited THEN they launch, so you can still do the typical "hit and then back-away" micro management you can do to deal with normal creepers when not having reliable or cost effective ranged weapons handy. 

it would certainly save me a lot of grief with rockets being practically impossible to react to cause by the time you hear and react they're already in the stratosphere and locked onto you. :V

**Comment by Daveyx0** [comment]
Good idea; will look into it

**Comment by Daveyx0** [comment]
They will wait a second before launching up in the next version

**Comment by Darkmega18** [comment]
Alrighty, sounds fair enough. :D
