### ISSUE TITLE
trade glitch 

### ISSUE THREAD

**Issue by Spongebobfan907** [Daveyx0/PrimitiveMobs#109]
the trades for the miner and traveller are somehow going to the farmers

**Comment by Daveyx0** [comment]
Did you change any config settings? What mods do you have? Was it on a reload or on a first encounter?

**Comment by Spongebobfan907** [comment]
if there naturally spawned the farmer's trades are what It should be but if I spawn them via spawn egg the trades from the travelling merchant and the miner goes to the farmers 
the only other mod that I have that has villagers is villager trades and the only config settings I changed was the vtt one

**Comment by Spongebobfan907** [comment]
the villager mod that i used to have was cubic villager

**Comment by Daveyx0** [comment]
I should probably check compatibility with those mods. If one of the mods overwrites some villager funtion then it will be hard for me to counter.

**Comment by Spongebobfan907** [comment]
ok

**Comment by Spongebobfan907** [comment]
I also used to have MinecraftComesAlive (which sucks) and it overwrites MOST of the villager functions

**Comment by Daveyx0** [comment]
I have still not been able to repro this; it's most likely on either cubic villager's or MCA's side from what I hear from you. Let me know if I'm incorrect.
