### ISSUE TITLE
Crash on Launch

### ISSUE THREAD

**Issue by ThisAlbino** [Daveyx0/PrimitiveMobs#111]
[Crash Log](https://paste.ee/p/C8Szw)

I've narrowed my crashes down to Primitive Mobs and I'm a bit stumped, never had problems with it before.

**Comment by Daveyx0** [comment]
Yeh this is my bad. Its an issue still present in 1.1.6. It can be fixed by disabling the summoning overlay in the config. Let me know if it worked.

**Comment by ThisAlbino** [comment]
Yeah that fixed it, thank you.
