### ISSUE TITLE
Ghost Brain Slime

### ISSUE THREAD

**Issue by WenXin20** [Daveyx0/PrimitiveMobs#113]
Forge v14.23.4.2750-1.12.2
Primitive Mobs v1.1.6_beta
The brain slime leaves behind a glitched-out death animation when it dies when attached to the player. I'm assuming this happens when killed by the thorns enchantment, which I have on my chestplate.
![2018-08-15_23 04 27](https://user-images.githubusercontent.com/12000593/44189126-4c223580-a0e7-11e8-9c17-96b42aa2919e.png)

**Comment by Daveyx0** [comment]
Hopefully fixed in all instances in the next version
