### ISSUE TITLE
Trade Glitch

### ISSUE THREAD

**Issue by Spongebobfan907** [Daveyx0/PrimitiveMobs#120]
ok I know you closed the original issue but I'm experiencing this bug again and I DON'T HAVE ANY OTHER MOD INSTALLED https://i.imgur.com/O6SP65I.png

**Comment by Daveyx0** [comment]
Still really confused by this one. Need to investigate. You do not have a consistent way of getting this? Is it random? Thanks for the report btw.

**Comment by Daveyx0** [comment]
I have found the issue and am working on a fix

**Comment by Daveyx0** [comment]
Fixed in the most recent version :)
