### ISSUE TITLE
[Suggestion] Option to change Lost Miner emerald reward

### ISSUE THREAD

**Issue by Mike-U5** [Daveyx0/PrimitiveMobs#121]
As the title says.

**Comment by naqaden** [comment]
Agreed. In our case the reward was too high and I ended up modifying the source to nerf it. A config for this would be very convenient.

**Comment by Daveyx0** [comment]
Should be easy enough

**Comment by Daveyx0** [comment]
This feature is available in the 1.2 alpha. Can be changed in the config.
