### ISSUE TITLE
[SUGGESTION] Configurable spawn rates

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#13]
Would it be possible to add configs back in for spawn rates?

I've also noted a bit of a slight lack of other mobs from other mods, at least on servers, with this mod installed.

Of note is that skeleton warriors seem to become pitch black at night, unless they are near a light source, compared to vanilla mobs, in which you can see their coloration to an extent.

**Comment by Daveyx0** [comment]
Thanks for the suggestion. I added the spawn rates to the config, although it really should not mess with other spawn rates as far as I know. 

Haven't fixed the skeleton thingy yet.
