### ISSUE TITLE
Tamed treasure slime duplicates items and items it doesn't take are deleted

### ISSUE THREAD

**Issue by f03n1x** [Daveyx0/PrimitiveMobs#130]
Not sure if this is supposed to happen exactly but with a tamed treasure slime if you right-click on the slime with an item it can take i.e. something like an iron ingot for instance when it has absorbed the item, if you right-click on it again with a stack of that same item, it will drop that amount on the ground, essentially duplicating by I think the amount you click on (if you right-click on it with a stack of diamond, you get another stack of diamonds back).

Also another issue related to tamed treasured slimes, if you right-click them with items they don't absorb (In my case I used a couple of vanilla items and a wand from Electroblob's Wizardry), it will deletes the item but also reset the slime back to being a default grey colour.

I'm using Primitive mobs 1.1.6_beta in the Roguelike Adventures and Dungeons modpack

Oh nearly forgot to mention this was done with the smallest slimes, I haven't tested it with bigger slimes due to not finding any bigger ones.

**Comment by Seriously0000** [comment]
It does the same thing with bigger slimes.

**Comment by Daveyx0** [comment]
Should be fixed in the 1.2 alpha :) Thanks guys!

**Comment by jaz000** [comment]
still happens for us on 1.2.3a :-)
