### ISSUE TITLE
Mod inflicting with "Pet Buddy" mod

### ISSUE THREAD

**Issue by Seriously0000** [Daveyx0/PrimitiveMobs#131]
I play in a modpack that has 46 mods in it. So, what happens is that, when the "buddy" attacks a mother spider or a baby spider and when a rocket creeper blows up in the range of the buddy "the possibilities are endless, try to fix all the mobs whenever possible", the game **crashes**. Once I restart the game, the tick updates without the "buddy". I have the crash log. If you want to see the log and/or want the video of what's happening, ask me! Oh, and the mod I was talking about the crash with is "_Pet Buddy_". Link for the mod here: https://minecraft.curseforge.com/projects/pet-buddy-mod

**Comment by Daveyx0** [comment]
Thanks for the report. Im not sure how the described conditions would cause an issue or why that would be Primitive Mobs related. Do you have a crash log? So I just have to make a buddy attack one of my spiders?

**Comment by random-player** [comment]
The bug was from an older version of Pet Buddy. I have got a new version set and now it's working fine. If you still want the crash report you can ask me.
