### ISSUE TITLE
Lost Miner Doorcheck crash

### ISSUE THREAD

**Issue by RodrigoTaipe93** [Daveyx0/PrimitiveMobs#132]
This is my crash:

- https://paste.dimdev.org/lufenanugi.mccrash

Just wanted to notify

**Comment by Daveyx0** [comment]
Hmm I cannot exactly see what's going on here but it appears the lost miner is trying to find a door to enter and things go wrong there.... thanks for notifying.

**Comment by Daveyx0** [comment]
I removed the door check altogether; next update you will only be able to save them by going to the surface again but at least this crash will no longer happen.
