### ISSUE TITLE
Trollager's melee swing should copy Iron Golem's mechanic

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#135]

**Comment by mser7** [comment]
Their reach should be as far as golems

**Comment by Daveyx0** [comment]
Increased their reach; but I wont make them launch you :P

**Comment by mser7** [comment]
No please make them launch me with their meaty arms :(

**Comment by mser7** [comment]
How about just a pathetic nerfed golem swing?
