### ISSUE TITLE
Disabling certain mobs in config causes crashing on both SSP and SMP

### ISSUE THREAD

**Issue by katubug** [Daveyx0/PrimitiveMobs#14]
Basically, the title. I found that disabling any mobs in the config causes my game to crash upon restarting. I'm gutted because I love the Grove Sprites, but the Chameleons are causing crashes (I'll make a separate issue for that) and the Rocket Creepers are just frustrating to play against.

Here are my SSP crash reports:

[crash-2017-11-27_22.17.32-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508496/crash-2017-11-27_22.17.32-client.txt)
[crash-2017-11-27_22.22.50-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508497/crash-2017-11-27_22.22.50-client.txt)

And from the server: 

[crash-2017-11-27_23.19.39-server.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508498/crash-2017-11-27_23.19.39-server.txt)
[crash-2017-11-27_23.23.04-server.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508499/crash-2017-11-27_23.23.04-server.txt)

**Comment by vivagabe** [comment]
Getting the same crash too.  Hopefully a resolution soon.

**Comment by Daveyx0** [comment]
Should be fixed in v1.1.3 beta. Thanks for reporting.

**Comment by katubug** [comment]
I hate to do this, but I think I need to re-open this issue. I re-added PM to my modlist this morning and while it was initially fine, I soon began having client crashes again.

The entity that was blamed in the crash log was an Animania Hamster, so I filed [this issue with them](https://github.com/capnkirok/animania/issues/466), but as you'll see from my comments, the solution was to have a PM config without any mobs disabled. I'm not sure if it's an interaction between the two mods that's causing the issue, or if it's the same mob-disabling issue as before.

**Comment by Daveyx0** [comment]
Looking at the way the author describes the issue it might be an inherent issue of mobs being added and removed from the entity registry. Not sure though. The only thing my config does is make sure the entity does not get registered and is therefore not a part of the game. A good temporary solution for you might be to just set their spawn rates to 0 for now and see if that works for you. They will still be in the creative menu then though.

**Comment by katubug** [comment]
Yeah, I saw that after I posted here. I guess I'll see what I can do to ameliorate the situation. Maybe if I remove Animania and get all the animals de-spawned, I'll be able to add both back in. Thanks for your help!
