### ISSUE TITLE
Non travelling merchants turn into farm profession villager

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#145]
I once tried out a villager spawner mod, and discovered there is a traveling merchant profession vanilla villager, but when I reloaded the game, the villager turned into a farmer villager.

**Comment by Daveyx0** [comment]
Hmm all vanilla villagers that get the traveling merchant profession should become farmers yes, however this should happen immediately and not only on reload. Will check, thanks!

**Comment by mser7** [comment]
This cause another problem, sometimes there will be a farmer that have the first tier trades of a merchant, can you make the merchant profession not appear in villages, or in breeding, spawning villagers?

**Comment by Daveyx0** [comment]
That last comment kinda makes sense. Will check

**Comment by Daveyx0** [comment]
Will be fixed in the next build :)
