### ISSUE TITLE
"Multimob: Invalid spawn entry found" spam all over the console

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#147]

**Comment by Daveyx0** [comment]
Hmm you didnt add a new spawn entry by any chance? This should not happen otherwise.

**Comment by mser7** [comment]
No, no I didn't.

**Comment by CritFlaw** [comment]
A friend is having the same issue. They disabled certain mobs, that's about it. Would it be possible that this can be caused by a server/client config difference? Also, it seems the lib mod multimob and the primitive mobs config both have options for disabling mobs, is that intentional?

**Comment by Phqntum** [comment]
When I edited the primitivemobs.cfg, disabling some spawns, that is when I noticed the issue. 

I fixed the console spam by reverting the primitivemobs.cfg to default, and disabling mob spawns in the multimob.cfg instead.

Hope this helps.

**Comment by Daveyx0** [comment]
Thanks for the info Phqntum. Might give me a better clue.

**Comment by Daveyx0** [comment]
In the new MultiMob I temporarely disabled the log spam until I find the proper issue. It's not a problem for functionality.

**Comment by Daveyx0** [comment]
Resolved next update
