### ISSUE TITLE
Chameleons cause client crash

### ISSUE THREAD

**Issue by katubug** [Daveyx0/PrimitiveMobs#15]
I'm not sure what's up, but my friends and I were all experiencing client crashes, it seems like upon the Chameleon changing colour?

Here are my crash reports:

[crash-2017-11-27_21.06.40-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508501/crash-2017-11-27_21.06.40-client.txt)
[crash-2017-11-27_22.15.05-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1508502/crash-2017-11-27_22.15.05-client.txt)

**Comment by Daveyx0** [comment]
Hopefully fixed in v1.1.3 beta. Thanks for reporting!
