### ISSUE TITLE
Sheepman professions appear in villager breeding, then turn into farmer profession

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#153]
https://imgur.com/a/FmUF99E
If I unlock the next tier trades, it will be the farmer's second tier trades, this is a similar problem to the merchant

**Comment by Daveyx0** [comment]
I kinda fixed this, but good thing you mentioned breeding cause my fix does not take that into consideration!

**Comment by Daveyx0** [comment]
Fixed in next update
