### ISSUE TITLE
A mob should always be introduced via registerModEntity

### ISSUE THREAD

**Issue by mr2013** [Daveyx0/PrimitiveMobs#154]
The current setup introduces the mob as a new addition to the world data, or removes it, effectively corrupting world data. This can be fixed by the server owner running /fml confirm on each config change. When a mob state is changed in the config, it should instead be reflected via a boolean in PrimitiveMobsSpawnEntry, to be later consulted by the same conditional as PrimitiveMobsWorldSpawner's rarity check.

**Comment by Daveyx0** [comment]
Ok, I kinda get what you are saying. Could you check for me if that's still the case with alpha 1.2? It uses this [class ](https://github.com/Daveyx0/MultiMob/blob/master/main/java/net/daveyx0/multimob/spawn/MMSpawnRegistry.java )  to check if the entityClass is registered and refreshes the spawnentries on reload. Wondering if I still made the same mistake somewhere.

**Comment by mr2013** [comment]
With the alpha, it still does this. As I'm testing with a local world, I can provide a screenshot this time around. It's the same message when a mob is disabled with the stable release.

https://gyazo.com/51d0577c588c08ec6ab0227c9baaeb65

**Comment by Daveyx0** [comment]
So what you mean is that the mob should never truely be removed and instead simply be disabled from spawning. However that will keep the spawn egg then... guess I could add multiple checks. Also I would need to make the existing mobs in that world save forcefully despawn. Willl look into it.

**Comment by Daveyx0** [comment]
Fixed in newest version v1.2.1, which requires MultiMob 1.0.3

**Comment by mr2013** [comment]
Thank you so much!
