### ISSUE TITLE
Server Crash on latest version

### ISSUE THREAD

**Issue by CritFlaw** [Daveyx0/PrimitiveMobs#155]
Minecraft 1.12.2
Forge 2780
Primitive Mobs 1.2 Alpha
Multi Mobs 1.0.1

Description:
Server just randomly crashed out of nowhere

Crash Log:
https://hastebin.com/avikopeyoq.rb

**Comment by Daveyx0** [comment]
Can you check if this still happens in the latest Beta version? I have no idea why the Grove Sprite would try to get that class on a server side... are all your players up to date?

**Comment by CritFlaw** [comment]
So far so good. That being said, the crash was kind of spontaneous and not really on initial startup, so we'll see if it happens at some random point.

**Comment by Daveyx0** [comment]
Thanks! It's a confusing issue for sure.

**Comment by LemADEC** [comment]
That's a bug in Grove sprite trying to use a client side only class in a dedicated server environment.

**Comment by Daveyx0** [comment]
Found the issue. Should be fixed in 1.2.2a.
