### ISSUE TITLE
Game Error

### ISSUE THREAD

**Issue by policeMarcus** [Daveyx0/PrimitiveMobs#156]
Minecraft got an Error...

Crash report
"Error Executing Task"
https://paste.dimdev.org/yataduqiqi.mccrash

**Comment by Daveyx0** [comment]
This should be fixed in the new version (1.2), could you check that for me? :) Thanks!

**Comment by policeMarcus** [comment]
Im playing the Modpack R.A.D on the twitch client, it is 1.12.2
