### ISSUE TITLE
Miner's turn to replace farm profession

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#157]
Same as other villagers, in villager breeding as well
![2018-12-24_16 15 09](https://user-images.githubusercontent.com/22555489/50396442-bdac7780-079c-11e9-8816-7182911e5598.png)
![2018-12-24_16 15 19](https://user-images.githubusercontent.com/22555489/50396443-bdac7780-079c-11e9-9dee-25f3d45a01fc.png)
For this issue, can you make the miner profession to still spawn in via villager breeding, but doesn't turn into farmer profession? Since this villager is supposed to be able to spawn in villages

**Comment by Daveyx0** [comment]
This will be fixed next update. You CAN have them spawn in villages; but only if you enable it in the config :)

**Comment by mser7** [comment]
But, will they also spawn in via a breeder and doesn't turn into a farmer profession? I will make an issue if they don't.
