### ISSUE TITLE
Remove merchant bribing with a block of emerald

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#158]
A block of emerald, which composed of 9 emeralds, will make a merchant stay in the world, but why don't you just use only 1 emerald to trade with him and have him stay?

Also merchant don't despawn after traded once

**Comment by Daveyx0** [comment]
Because then you would simply trade once and floud your world with merchants that never leave. These villagers are designed to be roaming, not to stay. So if you want them to stay; you will have to pay ;)

**Comment by mser7** [comment]
Merchant also trade for nametag, and IMO that work much better than the block

**Comment by Daveyx0** [comment]
Huh? That can't be possible; the traveling merchant clearly checks for a despawn and there is no code connected to doing a trade. That's not a part of my mod at least.
