### ISSUE TITLE
Invisible Baby Spiders and Black Grove Sprites?

### ISSUE THREAD

**Issue by Debilitated** [Daveyx0/PrimitiveMobs#159]
Just as the title says, I cant see baby spiders and the grove sprites are all black, please help!!

**Comment by Daveyx0** [comment]
Thanks for the report! I had this issue in the previous version as well but not anymore. Are you using the newest version of MultiMob? I no longer get this issue with the lastest version. If you ARE using the latest version, could you give me your mod list?

**Comment by Daveyx0** [comment]
Hope this is fixed? If not; I added some fail safes in the newest version that should 100% prevent this.
