### ISSUE TITLE
Trollager's swing should lauch you up a little

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#164]
Although their arms aren't as strong as golem's, they should still be able to make you fly a little bit into the air with those.

Yeah, I am not giving up on it yet.

**Comment by Daveyx0** [comment]
Although I appreciate your involvment with the mod and like a lot the suggestions you have given, I really would prefer you didn't spam the github with these kinds of things... I'm trying my best to keep the issue number as low as possible. 

That aside, I don't agree with this as the Trollager is difficult enough as it is right now.

**Comment by mser7** [comment]
Got it
