### ISSUE TITLE
Mystery egg crash

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#165]
https://pastebin.com/EZukJ9Gz

**Comment by Daveyx0** [comment]
This might be because one of the creepers is disabled? Will fix this in the next update so it still spawns the creeper when disabled; also have some other fail saves in place to prevent this.

**Comment by mser7** [comment]
Don't worry, it was on a test world

**Comment by Daveyx0** [comment]
Fixed in 1.2.1; it will however insta-despawn the creeper as it is technically disabled. Also update MultiMob please :)
