### ISSUE TITLE
Brain Slime eating some helmets

### ISSUE THREAD

**Issue by mxnmnm** [Daveyx0/PrimitiveMobs#167]
Alright I tested the latest version and it fixed it with some helmets such as advanced rocketry helmets but it broke other helmets such as the avaritia infinity helmet.  I haven't tested with other helmets but I'm pretty sure that you should fix it with avaritia just to be safe.

**Comment by mxnmnm** [comment]
Tested with blood magic armor and it does give those helmets damage so yea not just helmets that you wouldn't be expected to ever get in a legit survival world (at least a sane person's survival world)

**Comment by Daveyx0** [comment]
Why do these helmets circumvent durability?.... jeez, this seems almost more a problem on their end really. Will see what I can do.

**Comment by Daveyx0** [comment]
Thanks for the report btw ;P

**Comment by Daveyx0** [comment]
Honestly I've been checking this and I cannot get around it. Sorry :( the helmets for those mods should really return negative for when I check if the item is damageable; but instead it somehow results in a positive... I added another check in the latest version. Let's hope that helps.

**Comment by Daveyx0** [comment]
I DID fix the bug where the helmets would instantly disappear though :)

**Comment by TehNut** [comment]
You need to wrap [this call](https://github.com/Daveyx0/PrimitiveMobs/blob/master/src/main/java/net/daveyx0/primitivemobs/entity/monster/EntityBrainSlime.java#L301) in something like

```java
if (stack.getItem() instanceof ISpecialArmor)
    ((ISpecialArmor) stack.getItem()).damageArmor(...);
else
    stack.damageItem(...);
```

**Comment by Daveyx0** [comment]
Thanks for the clarification @TehNut
