### ISSUE TITLE
Invisible brain slime

### ISSUE THREAD

**Issue by Blatts12** [Daveyx0/PrimitiveMobs#17]
So, invicible brain slime is killing me. I disabled brain slime and it's still occur.
https://imgur.com/a/MjKB2

**Comment by Daveyx0** [comment]
Do you have more information on when it happened? Just during a normal encounter? Were you on a server? It appears to be difficult to reproduce as I have not encountered it yet.

**Comment by Blatts12** [comment]
Visible brain slime spawn too(so invisible spawn when slime is enabled too). Single player. Just during a normal encounter.

**Comment by Daveyx0** [comment]
Hoping 1.1.4 fixed this. If not, I will re-open.

**Comment by TheCorruption** [comment]
I'm still finding these in 1.1.5c, it's still called a brain slime in the death message though, and i'm not sure if its invincible or not, I was in survival single-player at a desert beach.

**Comment by BiladaAlada** [comment]
I'm using 1.16_beta for Minecraft 1.12.2 and I also get killed by invisible brain slimes, but I still need to disable it to see if it keeps happening or not

**Comment by naqaden** [comment]
I've just encountered this with 1.1.6 beta in MC 1.12.2 too. The first time, punching directly up seemed to knock it off as usual. The second time that didn't work for me, so I spam-punched in every direction which eventually worked.
