### ISSUE TITLE
Server crash java.lang.NoSuchMethodError: net.daveyx0.primitivemobs.entity.passive.EntityGroveSprite.getColor(Lnet/minecraft/world/World;Lnet/m

### ISSUE THREAD

**Issue by ProsperCraft** [Daveyx0/PrimitiveMobs#170]
Crash report-
https://gist.github.com/ProsperCraft/c95af8837f2045000a6cd10082ab5777

Console at time of crash- 
https://gist.github.com/ProsperCraft/5b6820ddb8c94841a1a1c90e3c5fdb2a

**Comment by Daveyx0** [comment]
I see what Im doing wrong here. Will fix asap. Thanks!

**Comment by Daveyx0** [comment]
Should be fixed in v1.2.2
