### ISSUE TITLE
NoSuchMethodError: net.daveyx0.multimob.util.EntityUtil.removeWhenDisabled(Lnet/minecraft/entity/Entity;)V

### ISSUE THREAD

**Issue by xkforce** [Daveyx0/PrimitiveMobs#172]
https://paste.dimdev.org/ilireqeteh.mccrash

primitivemobs-1.2.2a

**Comment by Daveyx0** [comment]
Did you intend to close this? If not, Ill have to take a look.

**Comment by xkforce** [comment]
I realized the multimobs dependancy hadn't updated to 1.0.3 which is why it was crashing which is why I closed the issue.
