### ISSUE TITLE
first time here.

### ISSUE THREAD

**Issue by eveecraft** [Daveyx0/PrimitiveMobs#173]
https://paste.dimdev.org/palepirile.mccrash
I'm new to most of this stuff, but i'll leave this here.

**Comment by Daveyx0** [comment]
Do you have the latest version of MultiMob? v1.0.3.  I changed the method the crash is talking about to not only take EntityLiving but simply any Entity; so that might explain it.

**Comment by eveecraft** [comment]
No I didn't thank you.
