### ISSUE TITLE
Missing dependency

### ISSUE THREAD

**Issue by pmcma2271** [Daveyx0/PrimitiveMobs#176]
When i run minecraft it says it is missing dependency **multimob**, but there is no lined dependency linked on the website that I can find

**Comment by FallenPixelsGit** [comment]
Here is the link to it. https://minecraft.curseforge.com/projects/multi-mob-core

Next time just google it.

**Comment by Daveyx0** [comment]
For some reason the dependency does not show up on the site; possible cause its a beta? It's listed in the files section though. Sorry!
