### ISSUE TITLE
Config option to turn off Grove Sprites ability to plant saplings

### ISSUE THREAD

**Issue by xAlicatt** [Daveyx0/PrimitiveMobs#178]
While an interesting idea, I do not care for the grove sprites ability to plant saplings. They spawn quite frequently and I'm having random trees pop up in places around my base where I don't want them. I don't want to disable the mob, just keep it from being able to plant. 

Does the planting respect the mobgriefing gamerule? If so, I can just use that as a workaround until/if a config option is added for this request

**Comment by Daveyx0** [comment]
Ah right, thanks! Makes sense, will add the config option in the next version. Sorry for the inconvenience.

**Comment by xAlicatt** [comment]
So I did just test it with mobGriefing set to false and they can still plant, so yeah having the ability to turn this off with a config would be awesome :D

**Comment by Daveyx0** [comment]
This is in the latest 1.2.3 build btw :)
