### ISSUE TITLE
Crash after disabling a mob

### ISSUE THREAD

**Issue by belathus** [Daveyx0/PrimitiveMobs#18]
https://cdn.discordapp.com/attachments/198533670498336768/386656329558917130/crash-2017-12-02_18.12.58-server.txt

I disabled the chameleon, rocket creeper, and festival creeper and got the above crash.

**Comment by Daveyx0** [comment]
Update to the 1.1.3beta. Should fix it :)

**Comment by belathus** [comment]
Ah, my bad. Thanks!
