### ISSUE TITLE
Dodo Cannot Lay Eggs

### ISSUE THREAD

**Issue by Dudblockman** [Daveyx0/PrimitiveMobs#182]
Dodos are advertized with the line "They also, very infrequently, lay Dodo Eggs."
I experimented with them and could not get them to lay a single egg. Upon looking into the code, there seems to be a mixup between this.timeUntilNextEgg and this.timeUntilNextDodoEgg, as in every onLivingUpdate this.timeUntilNextEgg is set to 100, and this.timeUntilNextDodoEgg is never decremented. As a result, the if statement on line 101 can never execute, and eggs will never be laid by the Dodo.

**Comment by Daveyx0** [comment]
Well thats a blunder. Thanks! Fixed it for the 1.2.3 beta release
