### ISSUE TITLE
Blood Magic Helmets and Brain Slimes Update

### ISSUE THREAD

**Issue by mxnmnm** [Daveyx0/PrimitiveMobs#184]
In case you missed TehNut's comment on the last issue that you closed here it is
https://github.com/Daveyx0/PrimitiveMobs/issues/167#issuecomment-450620077
Just wanted to be sure that you saw it so you can fix the issue.

**Comment by Daveyx0** [comment]
Bless you for reminding me

**Comment by Daveyx0** [comment]
Will be in 1.2.4
