### ISSUE TITLE
Mimic crash?

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#195]
https://pastebin.com/praVifkE

**Comment by mser7** [comment]
solved by rerolling back to 1.2.1

**Comment by Daveyx0** [comment]
No idea whats wrong here. How can the mimic class be missing... I also see you are using an outdated multimob but Im not sure how that would affect it. The mimic works just fine afaik.

Edit: nvm it is caused by an outdated Multimob version

**Comment by mser7** [comment]
there's also this
https://pastebin.com/M7K1EM6p

don't mind the outdated multimob, I swap around the version to investigate the crash, latest multimob also cause the crash

**Comment by Daveyx0** [comment]
That says Primitive mobs is at 1.2, meaning its outdated. It cannot find an interface that is only in the newer versions.

**Comment by mser7** [comment]
Again, I have to reroll versions to fix it, it do not work too

**Comment by mser7** [comment]
Can you reopen this? You did not find a solution for this?

**Comment by Daveyx0** [comment]
Sorry for the inconvenience but I can Only re-open it once you give me the same crash with both multimob and primitive mobs on their latest revisions. Cause the only reason it can have a nosuchmethod error is due to version incompatibility or install mistakes as far as I know.

**Comment by mser7** [comment]
here it is, it is the first crash I got after install the latest versions
https://pastebin.com/a64rQEeY

**Comment by Daveyx0** [comment]
Ah yes thanks this one is quite different :P to fix it you should simply have to update Optifine! Hope that fixes it

**Comment by mser7** [comment]
Thanks it worked
