### ISSUE TITLE
Haunted tool dropped two tools

### ISSUE THREAD

**Issue by PapiDimmi** [Daveyx0/PrimitiveMobs#2]
I killed a haunted golden axe and got two golden axes. I used a Looting III sword, so that might’ve affected it, but I’m not sure.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2531
**Primitive Mobs version**: 1.1beta

**Comment by Vazkii** [comment]
This is intended

**Comment by PapiDimmi** [comment]
All right. I thought it might be.

It doesn’t really make any sense for a tool or weapon to drop itself twice, though, but oh well.

**Comment by Vazkii** [comment]
I'm just going by the fact it's explicitly coded to do so. Take it up with @Daveyx0 :P

**Comment by PapiDimmi** [comment]
I got **four** wooden pickaxes after killing a haunted wooden pickaxe. Are you sure it’s intended?

**Comment by Daveyx0** [comment]
Yeh I might want to nerf that.

**Comment by PapiDimmi** [comment]
Fixed in [1.1.2beta](https://minecraft.curseforge.com/projects/primitive-mobs/files/2503039). Thanks!
