### ISSUE TITLE
Grove Sprites and Nuclearcraft Radiation

### ISSUE THREAD

**Issue by Darkere** [Daveyx0/PrimitiveMobs#204]
Grove Sprites seem to conflict with Nuclearcraft Radiation when they are trying to place saplings. Not sure what's causing it.

![image](https://user-images.githubusercontent.com/4283717/51275992-bfe8a700-19d3-11e9-896e-21066aad8eb5.png)
https://sparkprofiler.github.io/?mCIYeTQaBR

Pack: ATM3 - Remix
Forge: 2769
Primitive Mobs: 1.2.2.
Nuclearcraft:2.12k

**Comment by Darkere** [comment]
Appears that the nulearcraft dev is already planning to remove the offending feature.

**Comment by Daveyx0** [comment]
Thanks!
