### ISSUE TITLE
Mobs ignoring some spawn blockers

### ISSUE THREAD

**Issue by Yamza** [Daveyx0/PrimitiveMobs#208]
Peace Candle from Random Things namely.

Modpack: ATM3 Remix 1.0.2
Forge: 2796
primitivemobs-1.2.2a
RandomThings-MC1.12.2-4.2.4

**Comment by Daveyx0** [comment]
I already have a potential fix lined up for this. Thanks for the report!

**Comment by Yamza** [comment]
Awesome!
