### ISSUE TITLE
Cinder Saplings in 1.7.10 (not a port request!)

### ISSUE THREAD

**Issue by esotericdesign** [Daveyx0/PrimitiveMobs#210]
Is there a way to obtain Cinder Saplings in Survival? I found a video explaining Grove Sprites abilities, but in 1.1 WIP version for 1.7.10 the sprites hold a torch once set on fire, and don't do anything other than attacking players and setting them on fire as if in revenge.
Also, can Grove Sprites replicate legally? There is a sapling in creative, which I can plant, but these seem unobtainable either.
Or was that version so WIP that some features can't find their realization at all other than by cheating?

UPD: found out that when I right-click a sprite with seeds, a message appears that this sprite has negative number of ticks to go for a sapling creation, another bug?

**Comment by Daveyx0** [comment]
To be honest I forgot a lot of this as well as I never documented it properly :P A Cinder Sapling can be obtained as a 1/10 drop from a Cinder Sprite. They replicate once they have planted 10 times; but sadly there appears to be a bug there with their sapling ticks.. I dont know if I ever come around fixing it, but it's good to know. Sorry for the inconvenience!
