### ISSUE TITLE
Floating Flowers from Botania CTD both player and near players

### ISSUE THREAD

**Issue by polyjitter** [Daveyx0/PrimitiveMobs#213]
[Crash log.](https://paste.ee/p/Kn06O)

Does not seem to handle the situation when a color cannot be sourced, crashing everyone in the near vicinity.

**Comment by Daveyx0** [comment]
Thanks. Got this on discord as well. Will try to fix asap.

**Comment by Daveyx0** [comment]
Fixed in the new version of MultiMob (so not Primitive Mobs)
