### ISSUE TITLE
Make special villagers do not appear in villager breeders ever

### ISSUE THREAD

**Issue by mser7** [Daveyx0/PrimitiveMobs#216]
I know that you fixed the issue where your profession won't take over the first tier trades when turning into farmer, but that's it, now they still spawn, its just that they turn into farmer instantly, and that disrupt the balance of villager profession spawned, in my breeder, I have got an absurd amount of farmer villagers comparing to other professions.

**Comment by Daveyx0** [comment]
I never set the profession of a villager I replace in that event. As far as I know it should choose randomly like always unless vanilla does something weird there. Will have to check

**Comment by mser7** [comment]
I have a hunch as well, I don't know if the more careers a villager has, the more likely it will be chosen, close this if you cant find anything

**Comment by mser7** [comment]
Closing this for now
