### ISSUE TITLE
SUGGESTION: Mob difficulty should be changeable with a slider bar

### ISSUE THREAD

**Issue by random-player** [Daveyx0/PrimitiveMobs#222]
This mod used to be less harder (1.1.6_b) than it is now (1.2.3a). The Skeleton Warrior is the one that gets me every time! Even at Easy mode (global difficulty), he shoots weakness arrows! Since I'm not too experienced into defense yet, I am pretty bad at it. That should be on a difficult level preset of 3 or 4 in the config menu (max being 5). Because of this, the Skeleton Warrior is my least favorite hostile mob right next to the Mother Spider. I want the mod to be a little bit easier for my tastes. I want you to make a difficulty preset system if you can. Changing diffculty preset from 2 to 3 for example would increase some of the hostile mobs health limit (20 to 25 and etc.) and some other perks.
4 including special thing like arrows with effects. 1 being easiest and 5 being hardest. Sorry if it's too long, rude and hypocritical. (My old comment. It will be a range from 0 to 50. Not from 1 to 5.)

**Comment by random-player** [comment]
You don't have to do it. I'm not hating on the mod itself. I like the mod, just that I hate some of the hostile mobs. (I'm scared about you...)

**Comment by Daveyx0** [comment]
I have indeed see more and more people die due to the warrior. I will have a look at difficulty settings soon (or just nerf the warrior). Thanks for reporting the issue

**Comment by random-player** [comment]
The difficulty preset should look like a slider going from 0 (easiest) to 50 (hardest). List ahead.

< = LESS than, > = MORE than

1. / <10 will be simple. Some mobs are blacklisted and will not have too much health and gives very low strength melee attacks.
2. / >15 should enable some harder mobs (remove them off blacklist) with less health and less attacks.
3. / >25 should make some mobs for example the Trollager have higher health (30 to 40 & etc.) and some more attacks.
4. / >35 should make the Skeleton Warrior shoot weakness arrows.
5. / >40 should make some mobs have higher health (40 to "50 or 60") and the Trollager have a little bit of a bigger explosion. Not enough to be like the Wither's explosion but like a bed in nether like explosion without the fire.

Ideas like that could make people be better off to lower their difficulty a little bit so they have a fair game that they can play with. This could be a major update if you know what I mean.

**Comment by random-player** [comment]
Your festive creeper is cute though.

**Comment by random-player** [comment]
If I don't recieve a comment two weeks from now, this issue would be closed.

**Comment by random-player** [comment]
I didn't recieve a comment for a month. Issue closing.
