### ISSUE TITLE
[SUGGESTION] Well, two suggestions really

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#23]
1. Allow one to tone down the amount of baby spiders that spawn with a mother spider
2. Allow one to disable spawns per dimension

**Comment by Daveyx0** [comment]
Nr. 1 I just added here locally. Why do you want the second one? Modded dimensions? My mobs should ignore Nether and End biomes at least.

**Comment by Sunconure11** [comment]
Modded dimensions, yeah.

**Comment by Daveyx0** [comment]
In the next release I made it so my mobs only spawn in the Overworld or Nether. More specific tweaking will be added in the future.
