### ISSUE TITLE
Experiencing crashes after any edits to loot tables

### ISSUE THREAD

**Issue by shencil** [Daveyx0/PrimitiveMobs#24]
filch lizard specifically, not sure about the others.  happens after changing weight or after adding modded items

**Comment by Daveyx0** [comment]
Cannot reproduce. Could you post the relevant part of primitivemobs.cfg? 

Also, thanks for using this feature and testing it 👍

**Comment by Daveyx0** [comment]
Seeing as I still cannot reproduce; I will close this for now. Re-open when encountered again, but please add a crash report.
