### ISSUE TITLE
Iron Golem Attacks tamed baby spider

### ISSUE THREAD

**Issue by ghost** [Daveyx0/PrimitiveMobs#244]
whenever I bring the baby spider to a village with an iron golem the iron golem attacks it 
https://www.dropbox.com/s/wcwsmjm14i4qjea/Minecraft%201.12.2%202019-04-22%2016-59-36.mp4?

Other mods
https://paste.dimdev.org/emebuvexad.rb

**Comment by Jackiecrazy** [comment]
On the same vein (I see the tamed mobs extend EntityMob), is it possible to have them implement ITameableEntity (or whatever it was)? Helps with friendly fire not hitting them.

**Comment by Spongebobfan907** [comment]
idk

**Comment by ghost** [comment]
idk

**Comment by Daveyx0** [comment]
Fixed in next update
