### ISSUE TITLE
Lighting and Mob Disabling Bug

### ISSUE THREAD

**Issue by TriggreCC** [Daveyx0/PrimitiveMobs#25]
[crash-2017-12-31_15.00.09-server.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1595027/crash-2017-12-31_15.00.09-server.txt)
I'm currently facing bugs using this mod, one bug is the lighting bug of the Skeleton Warrior. When I'm inside a cave, the lighting of the Skelly Warrior doesn't match the lighting of the cave, which results in crashing of the game. The other one is when I disable specific mobs (i.e. Skeleton Warrior, Rocket Creeper), what I experienced is that the mob is there but not there. What I mean is the disabled mob can shoot or hurt the player but the player can't see the mob. The hit box is there but the mob itself is not. And when I do /kill _@e[type=!Player,r=_n_], it says in the chat "Killed Unknown". And if I run away from it, the game will crash, it happens even though I created a new world. With all due respect, when you put the disable button in the config of the mod, did the disabling mean 'remove the mob itself but can still hurt or shoot the player'?

![2017-12-31_14 50 54](https://user-images.githubusercontent.com/34977205/34459983-6a75729a-ee3b-11e7-9b5d-9ff7e4e7bb30.png)
![2017-12-31_15 00 07](https://user-images.githubusercontent.com/34977205/34459984-6a99f8ea-ee3b-11e7-81e2-f97c81749342.png)

**Comment by Daveyx0** [comment]
Fixed in 1.1.4 beta which should be uploaded soon. Thanks for reporting!
