### ISSUE TITLE
tamed spiders count as hostile mobs

### ISSUE THREAD

**Issue by lag42** [Daveyx0/PrimitiveMobs#255]
this means you can't sleep near them and automated defenses will attack them, that gets annoying fast

this is also what's causing https://github.com/Daveyx0/PrimitiveMobs/issues/244

**Comment by katubug** [comment]
Additionally, the command `/cofh killall` removes them. My server runs that command automatically so no one can keep tamed baby spiders. :(

**Comment by random-player** [comment]
This also affects the Mystery Eggs which are the tamed creepers you get very rarely.

**Comment by Daveyx0** [comment]
Very late response here. I cannot easily fix the killall thing from katubug unless that checks for IEntityOwnable; but this will be fixed for the next update.
