### ISSUE TITLE
1.1.4 beta - server crash on start

### ISSUE THREAD

**Issue by Febilian** [Daveyx0/PrimitiveMobs#26]
Crash log:
https://gist.github.com/Febilian/d946b4afc0c5779cf79429a57f5dad12

I _think_ it's got to do with the server trying to do something that's only supposed to happen on the client, from what I can understand.

**Comment by Daveyx0** [comment]
Thanks for the quick report. A fix should be up soon (1.1.4a beta). Stupid mistake. Thanks!
