### ISSUE TITLE
Grove Sprites Crash

### ISSUE THREAD

**Issue by mxnmnm** [Daveyx0/PrimitiveMobs#264]
I attacked a grove sprite in creative mode and it crashed ;-;
I can't repeat it so hopefully the crash report will be good enough

https://paste.dimdev.org/doyurihiku.mccrash

**Comment by Daveyx0** [comment]
Sorry that it took so long to reply, I took a long break. Sadly the link is broken so I will close this for now. Feel free to re-open when needed.
