### ISSUE TITLE
Incompatible with Respawnable Pets

### ISSUE THREAD

**Issue by inkdear** [Daveyx0/PrimitiveMobs#267]
https://www.curseforge.com/minecraft/mc-mods/respawnable-pets

Seems to work with other modded mobs, but not with the chameleons, mystery egg creepers or baby spiders from Primitive Mobs. It'd be nice if they worked together. Unfortunately, the other mod doesn't have an issue tracker, or I'd report it to them too.

Edit: they have a link to the issue tracker now 

Edit: it seems it works with the treasure slime, just not any of the others.

**Comment by Daveyx0** [comment]
Made this work for the next update for what it's worth xD a year old post
