### ISSUE TITLE
1.14a beta - server shutdown after an explosion

### ISSUE THREAD

**Issue by NotAVerb** [Daveyx0/PrimitiveMobs#27]
There was an explosion offscreen during the night. The singleplayer server promptly shutdown.
MultiMC did not crash.

The log mentions particle effects.
https://gist.github.com/NotAVerb/55836cc0d6f47dcdd2b4f8ea257f48ee

**Comment by Daveyx0** [comment]
Thanks for the report. I think I have at least a fix for the crash; however now the particles don't appear. Will fix asap.

**Comment by Daveyx0** [comment]
Should be fixed in 1.1.4b_beta once its up.
