### ISSUE TITLE
Tamed baby spider, and all baby creepers are considered hostile mobs.

### ISSUE THREAD

**Issue by Ethomas2000** [Daveyx0/PrimitiveMobs#272]
All the pets you can get in the mod are considered hostile and are targeted by golems and any other mob that attacks hostiles. It also will de spawn them if the world is set to peaceful this is very troublesome with base defense mods and when playing on a server with friends who have golems guarding their homes. Please make them like wolfs or any other pets, please.

**Comment by Daveyx0** [comment]
I cannot change the Peaceful despawn ruling; but I was able to fix the other stuff.
