### ISSUE TITLE
Crash at forge launch

### ISSUE THREAD

**Issue by d0ob** [Daveyx0/PrimitiveMobs#277]
Hello there !

Minecraft fail to start when trying Primitive mob.
The library to be precise, I can assume it's because of the forge version maybe ? 
I'm using the latest recommended one, having trouble with the all latest, is it ?

[crash-2019-10-31_14.00.18-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/3793845/crash-2019-10-31_14.00.18-client.txt)

https://pastebin.com/mzbh1wXV

**Comment by d0ob** [comment]
Oups, didn't ment to add the log as an attachment, I can make a pisetbin if prefered ! 
Well I'll do anyway now I think of it ^^ Here it is: https://pastebin.com/apke5uEA

**Comment by d0ob** [comment]
Also I tried looking it up, through multiple pages, but I never managed to make a search on github... 
I'm sorry if you allready answered it multiple times.

**Comment by Daveyx0** [comment]
Mega late response from me, sorry. But yes this was due to the forge version; it should have been fixed with a more recent one.
