### ISSUE TITLE
Can't sleep with support creeper nearby

### ISSUE THREAD

**Issue by mymindstorm** [Daveyx0/PrimitiveMobs#278]
Right clicking a bed with a support creeper following me creates the "You cannot rest now, there are monsters nearby" message.

**Comment by OlRusty** [comment]
> 
> 
> Right clicking a bed with a support creeper following me creates the "You cannot rest now, there are monsters nearby" message.

any mob nearby whether modded or vanilla mobs wont let you sleep nearby when monsters are around

**Comment by mymindstorm** [comment]
Non-hostile mobs let you sleep around them. You can even sleep around some hositle mobs too. https://minecraft.gamepedia.com/Bed#Sleeping

**Comment by Daveyx0** [comment]
Thanks for the report; will be fixed in next update.
