### ISSUE TITLE
[Suggestion] Adjust EACH MOBS spawnrate

### ISSUE THREAD

**Issue by Zack7292** [Daveyx0/PrimitiveMobs#280]
the title is self explaining, simply add a way to modify spawn rate of every mobs (if you want a base to help you, Grimoire Of Gaia have a way to adjust the mob spawn rate)

**Comment by Daveyx0** [comment]
You can already do this with Multimob; however I could look into a global reducer.

**Comment by Zack7292** [comment]
i actually find it after awhile in the library's config lol   (forgot this srry)
