### ISSUE TITLE
Pet Creepers are dysfunctional

### ISSUE THREAD

**Issue by Reshy** [Daveyx0/PrimitiveMobs#281]
Although I like the idea of support creepers, they don't seem to be functional as tamed mobs.  They don't attack other mobs, they still explode if you or a creeper hits them and they cannot be made to sit and wait for you like a wolf can.  It'd be nice if more functionality was added to them to make them actual useful, but as is anything but the support creeper is an active liability as they do nothing but wait for you to hit them and explode uncontrollably.  

Ideally, red creepers ought to throw their TNT at nearby mobs (ideally without damaging terrain), blue ones probably should fly towards enemies and explode non-suicidally, and the support creepers should keep near you and away from hostile mobs, as well as all of them not exploding themselves to your deficit.  Would be nice if you could heal them too like you can with wolves.

**Comment by Daveyx0** [comment]
Sorry for the mega late response. They already do all those things. Are you on the latest 1.12.2? You can make them sit with shift+right click. You can heal them with gunpowder. They only attack once they are adults; in their baby form they will not attack, you will have to wait for them to grow up.
