### ISSUE TITLE
[Suggestion] Blazing Juggernaut

### ISSUE THREAD

**Issue by GWSheridan** [Daveyx0/PrimitiveMobs#29]
A config option to turn its speed down of blazing Juggernaut as fighting it close up is difficult if early game. 
An if a pack author does a nether survival option hes a bit tough to beat when only have wood tools an such

**Comment by Daveyx0** [comment]
Although the Nether really is not meant for early-game exploration; I'll consider it.

**Comment by GWSheridan** [comment]
building forever stranded lost souls modpack an its based in the nether
