### ISSUE TITLE
Grove Sprites planting saplings can overwrite blocks

### ISSUE THREAD

**Issue by smoothuk** [Daveyx0/PrimitiveMobs#290]
It seems that this can happen to some blocks.  I had a double chest outside my base, which at some point had one half turned into a sapling.  The chest was on grass and I did see a couple of Grove Sprites wandering nearby, so I assume one of those cheeky chaps placed one there while I wasn't looking.

**Comment by Daveyx0** [comment]
Thanks for the report! Fixed in next release.
