### ISSUE TITLE
[CRASH] Chameleon/Camo Armor + Dog Bed (Doggy Talents) Crash

### ISSUE THREAD

**Issue by kil0byt3** [Daveyx0/PrimitiveMobs#291]
Please see below for info/logs.

https://github.com/CalaMariGold/Rebirth-Of-The-Night/issues/117

Let me know if there's any more info I can provide.

**Comment by Daveyx0** [comment]
Thanks for the report. Sadly I don't think I can fix this on my end as it seems to run into a nullpointer on the DoggyTalents end before it can give me the model info. I could help work around it if I knew more details but I havent been able to when looking at the code. For next release I will simply remove this code when doggytalents is installed which will still allow the chameleon to work on these models; but simply get a more generic color (from any side). Please re-open if you think more needs to be done.
