### ISSUE TITLE
Loot from mods not appearing in-game when added in config

### ISSUE THREAD

**Issue by Tres1B** [Daveyx0/PrimitiveMobs#31]
I tested this by spawning large amounts of mobs, but none appeared with the added items. This may just be a case of bad luck, but I spawned something between 100-200 of each, so I doubt that is the case. Strangely, they can spawn with items added in the config that are from vanilla.

[Here](https://pastebin.com/j9pqnBBh)'s a pastebin of the relevant part of the config, to check if I simply made a mistake in formatting.

**Comment by Daveyx0** [comment]
I'll look at this asap. Did you perhaps see a logger message in your logs? Something like: Treasure Slime treasure entry does not exist? Thanks for the report.

**Comment by Tres1B** [comment]
You're welcome for the report. As for the logs, there doesn't seem to be anything like that in them.

**Comment by Daveyx0** [comment]
Hmm after testing with biomesoplenty:gem:0:8 I have not encountered a problem yet. Are you sure those are the correct modids? The best way to check this is too see if the Filch Lizard tries to steal the item in question. If you changed it in game, make sure you reload the game before testing. I really need to find a better way to change these. I might just move this to json files.

**Comment by Tres1B** [comment]
I tested it solely with the Glass Hearts gems, and it still didn't seem to be showing up. The mod IDs aren't wrong either, as far as I know- I checked the advanced tooltips. Is there anything else I could possibly be doing incorrectly?

**Comment by Daveyx0** [comment]
I have no idea right now with the information provided, especially if you say that vanilla items work and the logs do not show any entries. I'll see if I can maybe change the way this works for the next release while thinking of a reason why this would occur. Sorry for the inconvenience.

**Comment by Tres1B** [comment]
I tested vanilla items by adding "minecraft:snowball:0:100" under Haunted Tools. It was only for the purpose of seeing if it worked or not for the report so I had taken the entry out after (which was probably a bit silly, admittedly). If there's anything I could provide to help I'll be willing to bring it up.

**Comment by Daveyx0** [comment]
Could you try the same thing with a modded item? I mean the rediculous odds. maybe from a different mod to make sure.

**Comment by Tres1B** [comment]
I tried it with the Iron Ladder from Quark. I didn't get anything this time either.

**Comment by Insane-96** [comment]
Can confirm. Added vulcanite and carbonado from respective mods, never showed up

**Comment by Insane-96** [comment]
Can confirm for Haunted tools.
Didn't test for lizards, but they may have the same problem?

**Comment by Daveyx0** [comment]
I have not been able to fix this yet as it works fine here... I might just change the way this works entirely, but that won't be for 1.1.5

**Comment by Daveyx0** [comment]
This has been replaced by normal loottables in assets/primitivemobs/loot_tables/entities/special which hopefully can be replaced by a resourcepack for your own versions. Should be in 1.1.5b beta once approved.

**Comment by Febilian** [comment]
Do you have any idea how one would apply changes to the JSON loot table files from this mod onto a dedicated server? Last time I checked resource packs aren't loaded serverside, but I also haven't been up to date on how resource packs work and concede that the way they work may have changed in 1.12 if not an earlier version.

Actually, after testing in single player, I'm not convinced that any changes will load through resource packs at all. None of my custom items are showing up in treasure slimes, nor will filch lizards spawn with/steal them. Items that I removed with the JSON files have not been removed.

I based the files off the source on Github.

Here is a link to the resource pack I created for this, maybe there's something wrong with its formatting? I admit I'm not exactly experienced with the formatting of these JSON recipes/loot tables/etc.

https://www.dropbox.com/s/vzsdd40za7ye8xr/PrimitiveMobsCustomLoot.zip?dl=0

**Comment by Insane-96** [comment]
You can't. There's no way to change loottables via Resource Packs. You can use (in 1.13) data packs, but unless 1.13 you have to put your loottables in the `world_folder/data/loottables` (iirc)

**Comment by Febilian** [comment]
Thanks for the response, I'll try that.

**Comment by Daveyx0** [comment]
This just shows how long I have not used any of these features (years). Hope Insane's solution works, at least this is a good setup for 1.13 then.

**Comment by Febilian** [comment]
Yep, it worked to put in world_folder/data/loot_tables!
