### ISSUE TITLE
Skeleton Warrior 

### ISSUE THREAD

**Issue by PCAwesomeness** [Daveyx0/PrimitiveMobs#33]
In comparison to the regular skeleton and the Wither Skeleton, the Skeleton Warrior walks slowly when using its melee AI. Maybe you can make it sprint like a Wither Skeleton does when using a sword?

As well as this, its transition from ranged to melee isn't the smoothest, as when you activate its melee AI, it still strafes around like the new ranged AI for a few seconds before finally transitioning into a complete melee AI.

**Comment by Daveyx0** [comment]
Hey, good to see you are still around :) 

Will work on this.

**Comment by Daveyx0** [comment]
Should be fixed for 1.1.5c-beta which is being processed for upload.
