### ISSUE TITLE
Server crash when interaction with Traveling Merchant

### ISSUE THREAD

**Issue by spocane** [Daveyx0/PrimitiveMobs#35]
Dedicated Server crashed after a couple of trades with the Traveling Merchant.

[crash-2018-01-14_13.40.23-server.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1629809/crash-2018-01-14_13.40.23-server.txt)

**Comment by Daveyx0** [comment]
Thanks for the report. I think I see what's going on, will fix asap

**Comment by Daveyx0** [comment]
Should be fixed in v1.1.5b beta which is awaiting approval.
