### ISSUE TITLE
Bandits?

### ISSUE THREAD

**Issue by AguilaDaddy** [Daveyx0/PrimitiveMobs#36]
Hey! Well I thought this could be a good idea!
Bandits, perhaps they could be odd looking villagers who spawns near villages or in their own camps around your world, they steal you, and if they don't find the valuable items, they will try to kill you. Please let me know what you think of this suggestion
I love your mod, peace

**Comment by Daveyx0** [comment]
Thanks for the suggestion. Glad you like the mod.

Fun idea. Maybe, but I already have so many mobs planned :)
