### ISSUE TITLE
conflict with JEI

### ISSUE THREAD

**Issue by Hypsellis** [Daveyx0/PrimitiveMobs#37]
Primitive mobs loads incorrectly JEI and cause the game to crash when NEI is present.
https://github.com/TheCBProject/NotEnoughItems/issues/139

**Comment by Daveyx0** [comment]
I will try to take a look at it. However I'm not doing anything unconventional as far as I know. I would need to know what JEI is trying to accomplish. It tries to get an ingredient type in my VillagerProfessions registry, which is confusing. Will test.

**Comment by Daveyx0** [comment]
Rather than NEI this has to do with JEI Villagers. The Travelling Merchant overrides the getTrades method to choose random trades each time. I'll try to see what I can do; but might not be able to fix it soon. Just Enough Resources copes with my custom trades just fine.

**Comment by Daveyx0** [comment]
Removing the TradeList still results in a crash. So it is probably the Traveling Merchant anyway. I cannot remove the override of getTrades() for my Traveling Merchant. I need it for the random trades. I will close this as this is not going to be fixed unless the JEI Villagers dev does a similar check (maybe just a null check?) as Just Enough Resources, which does not crash using my Villagers (it just shows no trades for the Traveling Merchant and the Lost Miner is fine).

**Comment by mezz** [comment]
I investigated this and it was actually an issue in JEI, fixed in the latest version.
https://github.com/mezz/JustEnoughItems/commit/ce6aac12af057aaeefaf7e3e17a3726995b5daca
