### ISSUE TITLE
[Bug] Sometimes you can't hit baby spiders that are on the ceiling

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#38]

**Comment by Daveyx0** [comment]
Can you elaborate? I have not been able to reproduce this and the hitbox seems ok.

**Comment by Insane-96** [comment]
I'll send you a video asap

**Comment by Insane-96** [comment]
There it is: https://clips.twitch.tv/HorribleCuteDurianFUNgineer
As I rewatched the video, I noticed that as soon as the spider started moving I was able to hit him.

**Comment by Insane-96** [comment]
I noticed that they can attack you from too far away (this happens with normal spiders too sometimes)
Notice the last hit that I parried with the shield: https://clips.twitch.tv/ResourcefulHomelyTigerBuddhaBar

**Comment by Daveyx0** [comment]
Thanks Insane. The range issue should not be too hard; but the collision one is hard to reproduce and might just be a weird Minecraft issue of some sorts. Will keep trying.

**Comment by Insane-96** [comment]
Seems like they become invincible when they should be suffocating (like they did before the last update)
