### ISSUE TITLE
Treasure Slimes and Blocks

### ISSUE THREAD

**Issue by ElvenChaos** [Daveyx0/PrimitiveMobs#39]
With tameable treasure slimes, putting an item that is rendered as a full block when held (i.e. emerald block or cobblestone) renders the block above the slime instead of inside. Items with item sprites (i.e. emerald item or potions) are fine.

**Comment by Daveyx0** [comment]
Thanks for reporting. Will fix.

**Comment by ElvenChaos** [comment]
Thank you for the fun mod :D

**Comment by Daveyx0** [comment]
:) Should be fixed for 1.1.5c-beta which is processing for upload right now.
