### ISSUE TITLE
Cascading worldgen

### ISSUE THREAD

**Issue by Adaptivity** [Daveyx0/PrimitiveMobs#40]
While running mod this appears in log [Server thread/WARN] [FML]: Primitive Mobs loaded a new chunk (-16, 23  Dimension: 0) during chunk population, causing cascading worldgen lag. Please report this to the mod's issue tracker. This log can be disabled in the Forge config.
I think it's coming from [here](https://github.com/Daveyx0/PrimitiveMobs/blob/db1e91235f09b0186ae66a64660430ac51ac63ec/src/main/java/net/daveyx0/primitivemobs/world/gen/WorldGenMimic.java#L55-L60)
More info here: https://www.reddit.com/r/feedthebeast/comments/5x0twz/investigating_extreme_worldgen_lag/
Mod version 1.1.5b
Forge 2590

**Comment by Daveyx0** [comment]
Wondering why this happens. The presented code does what the reddit post says. It takes the chunk coordinate and adds a random int between 0 and 16 to that coordinate; then it loads the Mimic chest. I'm having trouble seeing how it could go into the negatives or over 16.

**Comment by Adaptivity** [comment]
Here few examples how it was fixed in other mods: [1](https://github.com/progwml6/Natura/commit/b4de1f3a446e6c70c323cf85037ec6d40ecada41) and [2](https://github.com/lumien231/Random-Things/commit/0ab8cca70b0c1572d1f109a0361e18f72f2893b7)
Maybe it will give you a clue.

**Comment by Daveyx0** [comment]
Thanks!

**Comment by Daveyx0** [comment]
I did the same thing so hopefully this is now fixed for 1.1.5c-beta which is processing for upload.
