### ISSUE TITLE
Primitivemobs crashes with Dokucraft resource pack

### ISSUE THREAD

**Issue by Boymann** [Daveyx0/PrimitiveMobs#42]
[crash-2018-01-16_14.04.59-client.txt](https://github.com/Daveyx0/PrimitiveMobs/files/1640606/crash-2018-01-16_14.04.59-client.txt)
Version: primitivemobs-1.1.4b_beta
Forge: 2568
This happens when they log in with The Dokucraft resource pack, Optifine is also present. For some reason I can't reproduce this on my own machine. Same server/mods and resource pack though. Two machines crash on login, and the only change is the resource pack being used.
Any ideas?

**Comment by Daveyx0** [comment]
Seems like it has to do with an item in the Treasure Slime. Ill check it out. Thanks for reporting. For now you can disable the Slime.

**Comment by Daveyx0** [comment]
I think I found what may be happening here. Should be fixed in next release.

**Comment by Boymann** [comment]
Thank you so much!
