### ISSUE TITLE
[1.1.5c] Mobs spawning where they probably shouldn't

### ISSUE THREAD

**Issue by NotAVerb** [Daveyx0/PrimitiveMobs#44]
I encountered hostile mobs on a mushroom island. This may be unintended behavior if PrimitiveMobs is supposed to mirror the vanilla behavior of keeping the Mushroom Islands clean of enemies.
(I did appreciate the fortuitous apples from a treasure slime when I was starting to get hungry though)

![2018-01-19_22 28 59](https://user-images.githubusercontent.com/30223331/35179665-7d904c96-fd96-11e7-97a8-fc911cff83b3.png)

**Comment by Daveyx0** [comment]
Thanks for reporting. Yeh, this is unintended. Will fix.
