### ISSUE TITLE
[1.1.5c] Stone Trollagers Bite Back

### ISSUE THREAD

**Issue by NotAVerb** [Daveyx0/PrimitiveMobs#47]
I expected that a paralyzed statue wouldn't start walking and slamming me around. I was very wrong. I also doubt that this is intentional, though it was amusing.
![2018-01-24_19 44 19](https://user-images.githubusercontent.com/30223331/35364895-897a1c22-0169-11e8-8c04-6b2d1b2561e7.png)
Interestingly the trollager seemed intent on walking back to the exact spot where it initially froze. This was after bouncing back after being hit with my pickaxe.

**Comment by NotAVerb** [comment]
On further testing he wasn't moving back to where he froze. Just moving and attacking while nudging into the wall behind where I died in the above picture. 
Once again this was only after I provoked the statue.

**Comment by Daveyx0** [comment]
Hmm I think that's only outside of dev environment which is strange... will look into it. Thanks for reporting!
