### ISSUE TITLE
[Suggestion] We need a journeymap resource pack for mob icons

### ISSUE THREAD

**Issue by choekstr** [Daveyx0/PrimitiveMobs#48]
The regular vanilla mobs show up as icons on journeymap but all the primitive mobs show up as placeholder icons.  We really could use a resourcepack to be added to modpacks and end user clients to provide support.  This would really refine things for the experience 🥇 

https://journeymap.info/Custom_Mob_Icon_Sets

**Comment by Daveyx0** [comment]
Thanks, I will look into this.

**Comment by Daveyx0** [comment]
Will be in next version.
