### ISSUE TITLE
Grove Sprite and Spider Family still appears after disabling them in the config

### ISSUE THREAD

**Issue by Revilous** [Daveyx0/PrimitiveMobs#49]
I disabled Grove Sprites and Spider Family in the config but then i still heard the sound of the Grove Sprites (when i actually just disabled them because of the sound)  and then i also got attacked by something invisible and when i died it said "slain by unknown". I'm not 100% sure if it was a spider but i think so. I also see something randomly getting dmg in the wall and then i found a string so that was probably a spider.

I also set the spawn rate to 0 but it didn't fix the problem. Please fix this problem or tell me how i remove the files of the mobs completely because i love the mod but i don't want to die to something invisible all the time.

**Comment by Daveyx0** [comment]
Thanks for reporting. Are you using the most recent version as this was an issue a few versions ago and did you change it in the in-game config; if so did you restart the game?

**Comment by Revilous** [comment]
I used 1.1.3 Beta and now i tried 1.1.5 and it seems to be fixed, thanks!
