### ISSUE TITLE
Grove sprites have an incorrect hitbox

### ISSUE THREAD

**Issue by PapiDimmi** [Daveyx0/PrimitiveMobs#5]
I can’t hit grove sprites. I had to hit the air above its head to kill it.

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Primitive Mobs version**: 1.1beta

**Comment by PapiDimmi** [comment]
I found some more grove sprites and could kill them just fine. Strange.

**Comment by Vazkii** [comment]
![2017-11-24_19 07 53](https://user-images.githubusercontent.com/1794735/33221861-d1eaf94e-d14a-11e7-8f88-b9322d945bc7.png)

Looks good to me. A bit too tall maybe, but fine.

**Comment by PapiDimmi** [comment]
Huh. I wonder why I couldn’t hit them before.
