### ISSUE TITLE
[Suggestion] Allows disabling Traveling Merchants entering homes

### ISSUE THREAD

**Issue by Lykrast** [Daveyx0/PrimitiveMobs#50]
My base is currently at ground level and uses wooden doors as entrances. The thing is, Traveling Merchants keep entering it and going inside during the night, which is extremely annoying as they keep respawning.

Having a config option to prevent them from doing that would be greatly appreciated, as I currently have to resort to disabling their spawn.

**Comment by Daveyx0** [comment]
Good one, thanks. I will probably make a config option :)
