### ISSUE TITLE
Crash because of EntityDataManager.createKey misusage

### ISSUE THREAD

**Issue by tyra314** [Daveyx0/PrimitiveMobs#53]
Please don't call `EntityDataManager`.createKey() for other classes. 

See here:
https://github.com/Daveyx0/PrimitiveMobs/blob/4476e6ad951f7b9b4fab92a21f2c281a555a0f27/src/main/java/net/daveyx0/primitivemobs/entity/monster/EntityPrimitiveTameableMob.java#L32

That causes crashes and all kind of issues, like me not being able to play. 😭
For reference, here is the crash: https://github.com/Alex-the-666/Ice_and_Fire/issues/460
and the issue at Forge: https://github.com/MinecraftForge/MinecraftForge/issues/4743

**Comment by williewillus** [comment]
yep, the data manager is intended to only be used on a subtree of your own classes. Registering keys on other classes will break a ton of mods in a variety of ways.
If you look in the createKey method there's even a warning for this situation.

Those two lines should be changed to `EntityPrimitiveTameableMob`. If you need to attach this data to ALL tameables, then I recommend using entity capabilities and syncing them yourself.

**Comment by Daveyx0** [comment]
Yeh this is just an oversight. Sorry. Will fix and thanks for reporting!
