### ISSUE TITLE
[Suggestion] Werewolves ?

### ISSUE THREAD

**Issue by AguilaDaddy** [Daveyx0/PrimitiveMobs#54]
Hello there!
I suddenly came up with this idea, and I personally think werewolves may be quite a great addition to the mod. Even more interesting if the player has the ability to turn into one.

**Comment by Daveyx0** [comment]
Hmm dunno. I'm not intending on adding player abilities to this mod. It's a cool idea tho. Maybe a testificate Werewolf some day :P
