### ISSUE TITLE
Divide-by-zero crash if tameable Treasure Slime chance percentage is set to 0

### ISSUE THREAD

**Issue by nihiltres** [Daveyx0/PrimitiveMobs#56]
Title says it all; the crash log is *very* clear, and the problem goes away immediately if I set the tameable treasure slime chance percentage to 1 as a compromise.

There's a decent chance the same crash might apply to other numeric inputs.

# SANITIZE YOUR INPUTS!

:)

**Comment by Daveyx0** [comment]
Thanks for reporting! Stupid oversight, once more :P Will fix.
