### ISSUE TITLE
Question regarding loot

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#57]
In the past, you were able to modify the loot drops of mobs. Do you plan on bringing that back? I noticed you took it out in more recent configs.

**Comment by Daveyx0** [comment]
This has recently changed to prepare for the 1.13 data packs. For now you can get the loottables from de source code here and adjust those. Then put them in your world folder like this: your_world_name/data/loot_tables (you have to make that folder probably).

**Comment by Daveyx0** [comment]
For more info check here: https://minecraft.curseforge.com/projects/primitive-mobs/pages/mod-info/changing-loot-tables-tutorial
