### ISSUE TITLE
dimension whitelist/blacklist for mobs spawning

### ISSUE THREAD

**Issue by Hypsellis** [Daveyx0/PrimitiveMobs#58]
There should have config for preventing mobs to spawn in dimensions they shouldn't.

**Comment by Daveyx0** [comment]
Which mobs are spawning where? All mobs except for the Blazing Juggernaut should only spawn in dimension 0 in the latest version (1.1.6). The Juggernaut only spawns in biomes with the type Nether. 

I mean I plan to add this feature anyway but they should not spawn outside of the overworld right now...

**Comment by Hypsellis** [comment]
I noticed they spawn in the Aether, I think they spawn in the Twilight Forest and Deep Dark too, and some others I don't remember. Anyway they spawn in almost all modded dimensions.

**Comment by Daveyx0** [comment]
I just did a check with the most recent version (1.1.6beta) and by default they definitely do not spawn in the Aether or Twilight Forest. So either you are using an outdated version (as this was an issue in an older version) OR some other mod you have adds my mobs to those dimensions.

**Comment by Hypsellis** [comment]
Nah I always use last version, anyway I will try again, and see if it occurs again. ;)

**Comment by Hypsellis** [comment]
Ok I retried again, and it seems to work fine now, unsure to know what happened.
