### ISSUE TITLE
I can't open Traveling Merchant's trading inventory.

### ISSUE THREAD

**Issue by Danoterminator** [Daveyx0/PrimitiveMobs#59]
I can't open Traveling Merchant's trading inventory on my sponge server. Lost Miner's trading inventory normally works.

**Comment by Daveyx0** [comment]
I would love to get some more information on this. I just started my own server and the Traveling Merchant seems to work fine. Any more details?

**Comment by Danoterminator** [comment]
I just use spongeforge-1.12.2-2611-7.1.0-BETA-2940 with BiomesOPlenty-1.12.2-7.0.1.2315-universal and primitivemobs-1.1.6_beta. Nothing else.

**Comment by LXGaming** [comment]
I currently have this issue as well, I looked at the differences between the Lost Miner and Traveling Merchant NBT Data and found the Offerings to be empty for the Traveling Merchant, This indicated that the trades list wasn't being populated and I believe this to be the issue [PrimitiveMobsVillagerProfessions.java#L105](https://github.com/Daveyx0/PrimitiveMobs/blob/master/src/main/java/net/daveyx0/primitivemobs/core/PrimitiveMobsVillagerProfessions.java#L105), In a Sponge Environment `getTrades` is not called as `populateBuyingList` (Which is the only method that calls `getTrades`) is overwritten by [MixinEntityVillager.java#L181](https://github.com/SpongePowered/SpongeCommon/blob/bleeding/src/main/java/org/spongepowered/common/mixin/core/entity/passive/MixinEntityVillager.java#L181), as a result `getTrades` is never called causing the trades list for the Traveling Merchant to never get populated.

**Comment by Daveyx0** [comment]
Thanks LXGaming. Appreciate it.
