### ISSUE TITLE
Infinite Server Crashing with 1.1.6.beta

### ISSUE THREAD

**Issue by kreezxil** [Daveyx0/PrimitiveMobs#63]
1.1.6.beta crashes dedicated server Forge 1.12.2 build 2624

Notes:
     a brain slime is attacking a unicorn mob from another mod while a player is joining the game and is causing the server to crash.

crash report:
https://gist.github.com/497f772af2315f41a8f5885c259f4d97

fml server latest:
https://gist.github.com/bd3a3dd00d33a04ffbc9dea7b9cf0a80

**Comment by kreezxil** [comment]
cross posted to the other mods forum at https://www.minecraftforum.net/forums/mapping-and-modding-java-edition/minecraft-mods/2447896-the-reindeer-breed-has-arrived-wings-horns-and?comment=508

**Comment by Daveyx0** [comment]
Either disable the brain slime animal attacking in the config or ask the other mod owner to do a check for if their mounted entity is a player. I cannot fix this sadly.

**Comment by Curunir** [comment]
Having this issue as well. The problem is that the unicorn mod doesn't have a proper issue tracker, so it tends to end up on yours, even though it's not your fault. But thanks for pointing us to the workaround. Brain Slime attacking animals is not a core gameplay feature in my pack anyway.
