### ISSUE TITLE
Trollager attacks create error messages

### ISSUE THREAD

**Issue by NotAVerb** [Daveyx0/PrimitiveMobs#64]
This message appears in the logs every time a trollager attacks.
https://gist.github.com/NotAVerb/8d85605dedefb9ab263db617beb6d269

**Comment by Daveyx0** [comment]
Strange.... thanks for reporting. Will take a look. Could it be that you have a mod that changes the breaking block particle somehow? Or maybe some block is somehow seen as Air... hmmst

**Comment by NotAVerb** [comment]
Just did a quick test with only PrimitiveMobs installed. The error is the same.

**Comment by Daveyx0** [comment]
Thanks for testing, will take a look at this

**Comment by Daveyx0** [comment]
Fixed in the next version
