### ISSUE TITLE
Invisible stone trollagers?

### ISSUE THREAD

**Issue by NotAVerb** [Daveyx0/PrimitiveMobs#65]
I've encountered 3x3x3 seemingly empty spaces that the player can walk into and get sort of stuck on until walking backwards. Building a roof over these spaces seems to wake up a stone trollager.
No error messages to report.
Has anyone else encountered this behavior?

edit: Closing and restarting my instance caused the stone trolls to become visible. Strange.

**Comment by Daveyx0** [comment]
Hmm not sure what could cause this. Was this on a server?

**Comment by NotAVerb** [comment]
This was a single player instance. I haven't encountered the issue again recently but that could be because I've set the trollagers to remain below ground.

**Comment by Daveyx0** [comment]
Got multiple reports of this ;I think it has to do with the spawning above ground somehow. Will check.

**Comment by Daveyx0** [comment]
Hopefully fixed in next version now that the spawning system has changed.
