### ISSUE TITLE
There seem to be some world generation errors.

### ISSUE THREAD

**Issue by hjpoe** [Daveyx0/PrimitiveMobs#66]
Things like trees spawning too close together, like diagonally at chunk borders, and floating leaves. I also found a half a villiage house, screenshot attached. 
![2018-03-02_14 28 05](https://user-images.githubusercontent.com/35583004/37500166-5523bb20-289e-11e8-8d39-1cfd65cc0cd6.png)

**Comment by Daveyx0** [comment]
So is Primitive Mobs the only mod you have? There is only one generation thing PM adds and that's Mimic Chests which is a single block. Are you sure this is caused by this mod? It sounds unlikely.

**Comment by hjpoe** [comment]
I have forge.

**Comment by Daveyx0** [comment]
Is that an older world from before getting a new version or installing primitive mobs? Older worlds might have this issue but thats not unique to Primitive Mobs.
