### ISSUE TITLE
[Suggestion] Make Hunted tools drop damaged tools and with less damage the more looting you have

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#68]
E.g. a diamond sword Hunted Tool would drop a 1~390 (max_uses / 4) uses left sword.
Looting I = 1 ~ 781
Looting II = 1 ~ 1171
Looting III = 1 ~ 1562

**Comment by Daveyx0** [comment]
Nice, I will probably implement this together with an option to disable/enable. Have lots of local changes so I might just implement manually instead of pulling.

**Comment by Insane-96** [comment]
The only check that I forgot to add is if there's a mod that adds higher level enchantments (like quark, you can get up to Looting 4)

**Comment by Daveyx0** [comment]
Implemented with next version.
