### ISSUE TITLE
Server Crash from rocket creeper and BOP sandy grass

### ISSUE THREAD

**Issue by IchigoGames** [Daveyx0/PrimitiveMobs#71]
Found a bug with primitive mobs rocket creeper and BOP-biomes o plenty biome grass block
the issue happed when a rocket creeper blew up a BOP grassblock-sandy grass as soon as it happed server crashed tested with tnt and other creepers no crash only happens when its a rocket creeper for now i just disabled the that mob but i thought you might want to know about it.

Minecraft 1.12.2
Forge 2627
primitivemobs-1.1.6_beta
BiomesOPlenty-1.12.2-7.0.1.2325-universal
Crash Report https://pastebin.com/9LEbSTma
heres something some one said after looking at crash report for me may help may not.
[it looks like it cant get the proper block state when it drops from the explosion]

**Comment by Daveyx0** [comment]
Thanks! This one seems pretty obscure. Will take a look.

**Comment by apple550** [comment]
I literally just had the exact same bug! Sad too, since that was my favorite mob. :( The animation is amazing. XD

**Comment by Daveyx0** [comment]
Having a hard time figuring out how to prevent this crash. I think it has to do with something fall() tries to access after the block exploded... however disabling all fall results seems to not fix the issue.

**Comment by Daveyx0** [comment]
Nvm fixed

**Comment by ZXQWAS** [comment]
Could you release the jar please? I've built my house in a silty grass biome and am getting this sometimes.

**Comment by Sunconure11** [comment]
Try pinging him? He has been responding to issues on and off lately.

@Daveyx0
