### ISSUE TITLE
Tamed chameleon that are seated follow you for a while when you get attacked.

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#73]
If you have a nearby tamed chameleon that's seated and you get attacked, it follows you for a bit until it stops and stands still again.

**Comment by Daveyx0** [comment]
This has to do with how the following AI code for Tameables is set up. It's also the case for the vanilla Wolf. Will have to make a custom sitting AI for this soon.

**Comment by Daveyx0** [comment]
Should no longer happen in v1.2 :)
