### ISSUE TITLE
[1.1.6_beta] unknown passengers eating gear and killing players

### ISSUE THREAD

**Issue by kreezxil** [Daveyx0/PrimitiveMobs#74]
I 100% believe this is the brain slime doing it and that the part where it is eating the gear is caused by a network handling error.

On my dedicated World of Dragons server, of which I am the mod pack developer, there are no errors being reported in the console.

The clients don't crash but there are lots of error messages in the client console.

The relevant part of a players client log is as follows as we are monitoring it explicitly now.
https://pastebin.com/7DM6nciN

The full client log: https://pastebin.com/ctDTL7Ds

**Comment by Daveyx0** [comment]
It appears to have to do with this: https://bugs.mojang.com/browse/MC-90683 where the entity is no longer rendered on client for some reason which causes issues. Unsure how to fix right now; need to investigate. I'm increasing its render distance weight which hopefully mitigates the issue for now.

**Comment by Daveyx0** [comment]
or rather I might be able to dismount the player when the brain slime is not longer able to be rendered.

**Comment by Daveyx0** [comment]
Hopefully this is fixed with the nex changes to the Brain Slime next version.
