### ISSUE TITLE
Can't name Treasure Slimes

### ISSUE THREAD

**Issue by laserlemons** [Daveyx0/PrimitiveMobs#76]
It just deletes the nametag when you try to name a treasure slime.

1.1.6beta minecraft 1.12.2

**Comment by Daveyx0** [comment]
I cannot seem to reproduce this. On my end the Treasure Slimes get their name set properly.

**Comment by laserlemons** [comment]
After testing with no other mods I can't reproduce it either. Must just be an issue with my mod list.
