### ISSUE TITLE
[SUGGESTION] Oredict dodo eggs under the following oredicts

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#78]
egg
foodSimpleEgg
ingredientEgg
listAllegg
bakingEgg

This should allow your mod's eggs to be used in various recipes, provided by both vanilla and mods.

**Comment by Daveyx0** [comment]
Ah yeh I have not worked with OreDict in a while. Will look into it.

**Comment by Daveyx0** [comment]
Will be in next build
