### ISSUE TITLE
Suggestion: Make Blazing Juggernauts unlit, like the Blaze.

### ISSUE THREAD

**Issue by Paperdomo101** [Daveyx0/PrimitiveMobs#79]
World lighting does not affect the Blaze, and it is fully visible in the darkness of the Nether. It would be an improvement if the Blazing Juggernaut shared this attribute (which, in the Blaze's code I think is controlled with getBrightnessForRender).

**Comment by Daveyx0** [comment]
Makes sense; has been implemented for the next release
