### ISSUE TITLE
Possible cross-compat issue with this mod and the reptiles mod

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#8]
https://pastebin.com/rMdmVHx7

https://github.com/m1k3s/reptiles/issues/10

**Comment by Vazkii** [comment]
I believe this was fixed with https://github.com/Daveyx0/PrimitiveMobs/commit/975a74beac304419933a297fff17d4f464cf27a5

**Comment by PapiDimmi** [comment]
I also crashed after installing Reptile Mod.

**Crash log**: https://pastebin.com/raw/ZCNH7eF2

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Primitive Mobs version**: 3.8.4-78

**Comment by PapiDimmi** [comment]
Fixed it version [1.1.2beta](https://minecraft.curseforge.com/projects/primitive-mobs/files/2503039). Thanks, @Vazkii!
