### ISSUE TITLE
NPE with tinkers defense

### ISSUE THREAD

**Issue by Rikshy** [Daveyx0/PrimitiveMobs#80]
I wasnt sure wether to post it here or on TD github.
it crashes on game load.

https://pastebin.com/ygVzvxEt

As it says sth about slimes i tried loading the game with both of your slime mobs deaktivated - still crash.

let me know if this is actually a TD issue.

**Comment by Daveyx0** [comment]
If I remember correctly this has to do with the experimental summon overlay in my mod. Can you try and disable that in the config and check if it works?

**Comment by Rikshy** [comment]
You were right! 

I thought changing that setting would have no effect since your summons feature is disabled by default
```
` # Enable/Disable experimental Summons feature (requires reload)
    B:"Enable (beta) Summons (requires reload)"=false`
```

Thanks you for the quick reply and sorry for the false report :S

**Comment by Daveyx0** [comment]
Np this is my bad really. The summon feature will probably move to another mod next update.
