### ISSUE TITLE
Incompatibility with Dimensional Doors

### ISSUE THREAD

**Issue by Runemoro** [Daveyx0/PrimitiveMobs#81]
Monoliths from Dimensional Doors stop spawning in Limbo when Primitive Mobs is enabled. 

Latest Dimensional Doors version: https://github.com/DimensionalDevelopment/DimDoors/releases/tag/3.0.8

Biome spawn list: https://github.com/DimensionalDevelopment/DimDoors/blob/e080ddaa4a94b03fe324b033c25deeaf12117973/src/main/java/org/dimdev/dimdoors/shared/world/limbo/BiomeLimbo.java#L28

Monolith: https://github.com/DimensionalDevelopment/DimDoors/blob/225b5954c0d2e47bce340b3eec5f316719f373b3/src/main/java/org/dimdev/dimdoors/shared/entities/EntityMonolith.java

**Comment by Daveyx0** [comment]
Aside from it being an old issue; this is very unlikely as my mod does nothing to change those spawns. If it still occurs in the next version (which will be 1.2) let me know.

**Comment by Runemoro** [comment]
> this is very unlikely as my mod does nothing to change those spawns

I confirmed that this issue happens with only Dimensional Doors and Primitive Mobs and does not happen with just Dimensional Doors.

I'll let you know if it's still an issue in 1.2.
