### ISSUE TITLE
Item duplication 

### ISSUE THREAD

**Issue by ScharMeister** [Daveyx0/PrimitiveMobs#82]
If you have stack of 4 or more items, you can duplicate them by spamming the right mouse button on a friendly slime. Seems like it's holding the entire stack, while right clicking only uses up a single item. 

![2018-04-27_22 58 12](https://user-images.githubusercontent.com/38443361/39384899-a0a8297c-4a6e-11e8-8e2b-820098fc5c63.png)

**Comment by Daveyx0** [comment]
Whoops! Thanks for the report!

**Comment by Daveyx0** [comment]
Fixed in next version

**Comment by Minamikaze392** [comment]
Is there an estimated date for next version?

**Comment by Daveyx0** [comment]
Sorry that it took so long. Fix is in the 1.2 alpha.
