### ISSUE TITLE
Weird crash

### ISSUE THREAD

**Issue by Sunconure11** [Daveyx0/PrimitiveMobs#85]
https://pastebin.com/Sn7my2dD

**Comment by Sunconure11** [comment]
https://github.com/Glitchfiend/FamiliarFauna/issues/17

**Comment by Forstride** [comment]
This was fixed on Familiar Fauna's end (Butterflies had a health value of 0.5D before), although you should probably add some kind of additional check to make sure this doesn't happen in the future with any other mods.

**Comment by Daveyx0** [comment]
Should have never implemented the summoning thing alpha into the build. :/ Sorry for the inconveniences. Will do a check on my end for later builds

**Comment by Daveyx0** [comment]
Fixed for next update because the summoning stuff will be gone; also fixed it in my backup code anyway if I ever want to use it.
