### ISSUE TITLE
exception while adding particle

### ISSUE THREAD

**Issue by kreezxil** [Daveyx0/PrimitiveMobs#86]
https://pastebin.com/mqBih9zt

**Comment by Daveyx0** [comment]
Will take a look. Thanks! Sorry for the late response

**Comment by Adarcer** [comment]
Did not crash game but here is another particle exception .. possibly caused by creeper explosion because there was a explosion then the warning. I turned off creepers so that may help.

https://paste.dimdev.org/xutugufojo.mccrash

**Comment by jaz000** [comment]
We get this too - kicks people out of the game
lots of other mods involved in case of interaction
https://pastebin.com/FUmLnUCy
Vanilla fix catches it (if you use that mod as well)

**Comment by Daveyx0** [comment]
Fixed in next version
