### ISSUE TITLE
Trollager "Destroy Terrain" Crash

### ISSUE THREAD

**Issue by SextupleTap** [Daveyx0/PrimitiveMobs#88]
The Trollager crashes the game at random when the "destroy terrain option is enabled."
The Trollager can successfully destroy the terrain multiple times in a row without any crash, but at random moments when the Trollager destroys terrain the game then crashes right after.

Here is the paste if the crash log (VanillaFix is used to collect the crash log):

https://paste.dimdev.org/itugelayol.txt

When you disable the "Trollager destroy terrain with smash attack" option the crash WILL never happen. I tested this for an hour straight, I kept crashing with the option on at random smash attacks, when I turned the option off many and then spawned many Trollagers, the smash attacks never crashed the game.

The crash DID happen without VanillaFix, while the mod was completely on its own isolated from any other mods, this includes Optifine as well. Again, the crash still happened when the mod was completely on its own, even without Optifine and VanillaFix.

**Comment by Mattabase** [comment]
I can confirm this crash is present with just the mod, here is a crash I can reproduce in another modpack. 

Crash
https://paste.dimdev.org/jalijelaza.mccrash

MC Version: 1.12.2
Forge Version (e.g. 2604): 2703

**Comment by ZXQWAS** [comment]
I have this too.

**Comment by Daveyx0** [comment]
Thanks for the report. Sorry for the wait. Will check it out.

**Comment by Daveyx0** [comment]
Fixed in next version
