### ISSUE TITLE
You shouldn't be able to get loot when using a Mimic Orb

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#91]
You can get free loot by right clicking on a check with a Mimic Orb.
Makes no sense. Instead loot in the chest should be what the chest contained before the right-click

**Comment by Daveyx0** [comment]
Well there needs to be some use to the orb. What else would you propose? Thanks

**Comment by Insane-96** [comment]
I think it should keep the loot that's already inside

I mean, if in a chest there's a piece of dirt, on trasforming the chest
with a Orb, the dirt will stay and as soon as you get the treasure loot or
the trap you can get back the dirt.

Maybe even make that the mimic drops the content of the chest plus the orb
and the chest. It is mostly a joking item, I think (or making your friends
must kill the Mimic to take the reward :P).

That's my idea

**Comment by Daveyx0** [comment]
Wait can you use it on a chest with an item inside? It should check for that... and yeh the point of it being a joke item does make sense :p

**Comment by Insane-96** [comment]
> Wait can you use it on a chest with an item inside?  
Nope

**Comment by Daveyx0** [comment]
This can now only be done in creative mode.
