### ISSUE TITLE
Brain slimes still can attack you while dead

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#92]

**Comment by Daveyx0** [comment]
Will need some more info on this. Thanks for the report though

**Comment by Insane-96** [comment]
When they are in the dead position (90 degrees on the floor, before their
corpose disappears) they can still attack you

**Comment by Daveyx0** [comment]
Will add a health check then. Really strange. Thanks!

**Comment by Daveyx0** [comment]
Should be fixed in next version.
