### ISSUE TITLE
Brain slime eating helmet

### ISSUE THREAD

**Issue by mxnmnm** [Daveyx0/PrimitiveMobs#93]
If a helmet doesn't have durability I.E. Advanced rocketry's space helmet, a brain slime can destroy the helmet.

**Comment by SextupleTap** [comment]
A better solution would be to allow the brain slime to do damage when it detects an unbreakable "helmet" currently being worn.

**Comment by SextupleTap** [comment]
I guess a good solution to fix the Brain Slimes destroying unbreakable helmets would be to allow the brain slime to do damage to the player when it detects an unbreakable "helmet" currently being worn.

**Comment by Daveyx0** [comment]
Yeh I thought I had a check for this. Apparently not. Thanks for the report

**Comment by Daveyx0** [comment]
Should be fixed next update
