### ISSUE TITLE
Lost miner and traveling merchant despawn after begin settled

### ISSUE THREAD

**Issue by Insane-96** [Daveyx0/PrimitiveMobs#94]

**Comment by Daveyx0** [comment]
Will look into it. Thanks for reporting

**Comment by Protochaud** [comment]
Same here. Trapped a traveling merchant, gave him an emerald block, he disappeared.

**Comment by Darkmega18** [comment]
ok, yeah, I'm therefore getting this too. I had two really good merchants, I even went as far as to name tag them thinking name tagged mobs can't despawn and they still went poof... I even made them a shop called Gerald and Coe's emporium cause they had such good trades. T_T

**Comment by Daveyx0** [comment]
Finally will be fixed in the next version

**Comment by Darkmega18** [comment]
excellent. :D

**Comment by dualinfinities** [comment]
whew, I was just checking to see if this had been reported, glad to see someone else wanted to have them around.
