### ISSUE TITLE
Merchants everywhere

### ISSUE THREAD

**Issue by scribbler957** [Daveyx0/PrimitiveMobs#97]
I turned frequency down to 1, but I still see tons of them, sometimes two or three nearby each other.

**Comment by Daveyx0** [comment]
Hmm strange. Will take a look. Thanks for the report

**Comment by CrazyCowboy557** [comment]
It does seem to be the case. I've had two of them in my small house with another right outside. They show up almost annoyingly often.

**Comment by scribbler957** [comment]
I've been chopping up the ones dealing in bunny slaughter and with Pillagers they've made a fairly consistent emerald source. >:)

**Comment by CrazyCowboy557** [comment]
I have pillagers installed, but I've yet to get anything from them.

**Comment by Daveyx0** [comment]
Will be fixed with new spawning logic next update
