### ISSUE TITLE
When Disabled in config\fmlModState.properties by Player's Choice, Primitive Mobs crashes.

### ISSUE THREAD

**Issue by TeetoKaziim** [Daveyx0/PrimitiveMobs#98]
Mod List:
Forge: 14.23.4.2708
Player's Choice: 1.2-4
Primitive Mobs: 1.1.6_beta.jar

Crash Report: https://gist.github.com/TeetoKaziim/5272046a217f74a5ee3108fca3b13076

When disabling Primitive Mobs using Player's Choice, future startups of the modpack crash with this error.

**Comment by Daveyx0** [comment]
I should probably ask Vazkii about this one. Thanks

**Comment by Daveyx0** [comment]
Fixed in next update
